//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho_WFC.PatientService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://schemas.datacontract.org/2004/07/Trabalho_WFC.Models")]
    [System.SerializableAttribute()]
    public partial class Patient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime birthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string patient_unField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime register_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unit_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime birthday {
            get {
                return this.birthdayField;
            }
            set {
                if ((this.birthdayField.Equals(value) != true)) {
                    this.birthdayField = value;
                    this.RaisePropertyChanged("birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contact {
            get {
                return this.contactField;
            }
            set {
                if ((object.ReferenceEquals(this.contactField, value) != true)) {
                    this.contactField = value;
                    this.RaisePropertyChanged("contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string patient_un {
            get {
                return this.patient_unField;
            }
            set {
                if ((object.ReferenceEquals(this.patient_unField, value) != true)) {
                    this.patient_unField = value;
                    this.RaisePropertyChanged("patient_un");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime register_date {
            get {
                return this.register_dateField;
            }
            set {
                if ((this.register_dateField.Equals(value) != true)) {
                    this.register_dateField = value;
                    this.RaisePropertyChanged("register_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unit_name {
            get {
                return this.unit_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.unit_nameField, value) != true)) {
                    this.unit_nameField = value;
                    this.RaisePropertyChanged("unit_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PatientService.IPatients")]
    public interface IPatients {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatients/RegisterPatient", ReplyAction="http://tempuri.org/IPatients/RegisterPatientResponse")]
        void RegisterPatient(Trabalho_WFC.PatientService.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatients/RegisterPatient", ReplyAction="http://tempuri.org/IPatients/RegisterPatientResponse")]
        System.Threading.Tasks.Task RegisterPatientAsync(Trabalho_WFC.PatientService.Patient patient);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPatientsChannel : Trabalho_WFC.PatientService.IPatients, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatientsClient : System.ServiceModel.ClientBase<Trabalho_WFC.PatientService.IPatients>, Trabalho_WFC.PatientService.IPatients {
        
        public PatientsClient() {
        }
        
        public PatientsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatientsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegisterPatient(Trabalho_WFC.PatientService.Patient patient) {
            base.Channel.RegisterPatient(patient);
        }
        
        public System.Threading.Tasks.Task RegisterPatientAsync(Trabalho_WFC.PatientService.Patient patient) {
            return base.Channel.RegisterPatientAsync(patient);
        }
    }
}
